apiVersion: kubeadm.k8s.io/v1beta4
kind: ClusterConfiguration
clusterName: "{CLUSTER_NAME}"
kubernetesVersion: "{CLUSTER_VERSION}"
certificatesDir: "/etc/kubernetes/pki"
imageRepository: "{IMAGE_REPO}"
controlPlaneEndpoint: "{API_SERVER_ADDRESS}:6443"
etcd:
  local:
    imageRepository: "{IMAGE_REPO}"
networking:
  serviceSubnet: "{SERVICE_CIDR}"
  podSubnet: "{POD_CIDR}"
  dnsDomain: "{CLUSTER_NAME}"
