server:
  name: "infrastructure"
  version: 0.0.1
  env: cluster
  grpc:
    network: "tcp"
    addr: 0.0.0.0:9002
    timeout: 15
log:
  max_size: 500
  max_backups: 3
  max_age: 28
resource:
  url: "https://github.com/f-rambo/infrastructure/releases/download/v0.0.1/resource-v0.0.1.tar.gz"
  install: "install.yaml"
  vpc_cidr: "172.16.0.0/16"
